alter session set current_schema = ad;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

create user "4" IDENTIFIED by 4;
GRANT CREATE SESSION TO "4" container = all;

drop user tmp;

create role C##RL_NVCB;

select * from dba_roles;

grant C##RL_NVCB to "4";

--drop user c##4;
grant select on c##ad.NHANSU to tmp;
grant select on c##test.BH_DONHANG to C##RL_KHCN;

CREATE OR REPLACE PROCEDURE USP_CREATEUSER
AS
 CURSOR CUR IS (SELECT MANV
 FROM NHANSU
 WHERE MANV NOT IN (SELECT USERNAME
 FROM ALL_USERS)
 );
 STRSQL VARCHAR(2000);
 USR VARCHAR2(5);
BEGIN
 OPEN CUR;
 STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
 EXECUTE IMMEDIATE(STRSQL);
 LOOP
 FETCH CUR INTO USR;
 EXIT WHEN CUR%NOTFOUND;

 STRSQL := 'CREATE USER '||USR||' IDENTIFIED BY '||USR;
 EXECUTE IMMEDIATE(STRSQL);
 STRSQL := 'GRANT CONNECT TO '||USR;
 EXECUTE IMMEDIATE(STRSQL);
 END LOOP;
 STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
 EXECUTE IMMEDIATE(STRSQL);
 CLOSE CUR;
END; 

EXEC USP_CREATEUSER;

SELECT * FROM ALL_USERS ORDER BY USERNAME;

CREATE OR REPLACE FUNCTION NVCB1 (schema_var IN VARCHAR2, table_name IN VARCHAR2)
RETURN VARCHAR2
AS
  v_vaitro NVARCHAR2(50);
BEGIN
  SELECT VAITRO INTO v_vaitro
  FROM NHANSU
  WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

  IF v_vaitro = N'Nhân viên c? b?n' THEN
    RETURN '1 = 1'; 
  ELSE
    RETURN '1 = 0'; 
  END IF;
END;
/

SELECT NVCB1('C##ad', 'NHANSU') FROM DUAL;

CREATE OR REPLACE FUNCTION PC1_FUNCTION
 (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2
AS
  USER_VAL VARCHAR2(100);
  predicate VARCHAR2(4000);
BEGIN
  USER_VAL := SYS_CONTEXT('USERENV', 'SESSION_USER');
  -- Removing the 'c##' prefix
  USER_VAL := SUBSTR(USER_VAL, 4);
  predicate := 'MAKH = ''' || USER_VAL || '''';
  RETURN predicate;
END;

SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') FROM DUAL;

SELECT PC1_FUNCTION('C##ad', 'NHANSU') FROM DUAL;

SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') FROM DUAL;

BEGIN
 DBMS_RLS.ADD_POLICY(
 OBJECT_SCHEMA =>'C##test',
 OBJECT_NAME=>'BH_DONHANG',
 POLICY_NAME =>'PC1',
 FUNCTION_SCHEMA => 'C##test',
 POLICY_FUNCTION=>'PC1_FUNCTION',
 STATEMENT_TYPES=>'SELECT'
 );
END;

BEGIN
 DBMS_RLS.DROP_POLICY(
 'C##test','BH_DONHANG','PC1'
 );
END;
