BEGIN 
SA_SYSDBA.CREATE_POLICY( 
policy_name => 'notification_policy',  
column_name => 'notification_label' 
); 
END;

EXEC SA_SYSDBA.ENABLE_POLICY ('notification_policy'); 

-- create level
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',20,'TK','TRƯỞNG KHOA'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',40,'TDV','TRƯỞNG ĐƠN VỊ'); 
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',60,'GVN','GIÁO VIÊN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',80,'GV','GIÁO VỤ');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',100,'NV','NHÂN VIÊN');
EXECUTE SA_COMPONENTS.CREATE_LEVEL('notification_policy',120,'SV','SINH VIÊN');


-- create compartment
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',5,'HTTT','HỆ THỐNG THÔNG TIN'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',10,'CNPM','CÔNG NGHỆ PHẦN MỀM'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',15,'KHMT','KHOA HỌC MÁY TÍNH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',20,'CNTT','CÔNG NGHỆ THÔNG TIN'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',25,'TGMT','THỊ GIÁC MÁY TÍNH'); 
EXECUTE SA_COMPONENTS.CREATE_COMPARTMENT('notification_policy',30,'MMT','MẠNG MÁY TÍNH'); 



-- create group
EXECUTE SA_COMPONENTS.CREATE_GROUP('notification_policy',10,'CS1','CƠ SỞ 1'); 
EXECUTE SA_COMPONENTS.CREATE_GROUP('notification_policy',15,'CS2','CƠ SỞ 2');

-- CHECK
SELECT * FROM DBA_SA_LEVELS; 
SELECT * FROM DBA_SA_COMPARTMENTS; 
SELECT * FROM DBA_SA_GROUPS; 
SELECT * FROM DBA_SA_GROUP_HIERARCHY; 

-- CREATE LABEL
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TK:CS1') 
WHERE ID = 1; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TK:CS2') 
WHERE ID = 2; 

UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:HTTT:CS1') 
WHERE ID = 3; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:CNPM:CS1') 
WHERE ID = 4; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:KHMT:CS1') 
WHERE ID = 5; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:CNTT:CS1') 
WHERE ID = 6; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:TGMT:CS1') 
WHERE ID = 7; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:MMT:CS1') 
WHERE ID = 8; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:HTTT:CS2') 
WHERE ID = 9; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:CNPM:CS2') 
WHERE ID = 10; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:KHMT:CS2') 
WHERE ID = 11; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:CNTT:CS2') 
WHERE ID = 12; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:TGMT:CS2') 
WHERE ID = 13; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','TDV:MMT:CS2') 
WHERE ID = 14; 

UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:HTTT:CS1') 
WHERE ID = 15; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:CNPM:CS1') 
WHERE ID = 16; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:KHMT:CS1') 
WHERE ID = 17; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:CNTT:CS1') 
WHERE ID = 18; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:TGMT:CS1') 
WHERE ID = 19; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:MMT:CS1') 
WHERE ID = 20; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:HTTT:CS2') 
WHERE ID = 21; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:CNPM:CS2') 
WHERE ID = 22; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:KHMT:CS2') 
WHERE ID = 23; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:CNTT:CS2') 
WHERE ID = 24; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:TGMT:CS2') 
WHERE ID = 25; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GVN:MMT:CS2') 
WHERE ID = 26;

UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GV:CS1') 
WHERE ID = 27; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','GV:CS2') 
WHERE ID = 28;

UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','NV:CS1') 
WHERE ID = 29; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','NV:CS2') 
WHERE ID = 30;

UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:HTTT:CS1') 
WHERE ID = 31; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:CNPM:CS1') 
WHERE ID = 32; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:KHMT:CS1') 
WHERE ID = 33; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:CNTT:CS1') 
WHERE ID = 34; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:TGMT:CS1') 
WHERE ID = 35; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:MMT:CS1') 
WHERE ID = 36; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:HTTT:CS2') 
WHERE ID = 37; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:CNPM:CS2') 
WHERE ID = 38; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:KHMT:CS2') 
WHERE ID = 39; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:CNTT:CS2') 
WHERE ID = 40; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:TGMT:CS2') 
WHERE ID = 41; 
UPDATE TABLE_NAME 
SET region_label = CHAR_TO_LABEL('NOTIFICATION_POLICY','SV:MMT:CS2') 
WHERE ID = 42;